version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: lumina_db
    restart: always
    environment:
      POSTGRES_USER: lumina
      POSTGRES_PASSWORD: lumina_password
      POSTGRES_DB: lumina_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
